### ISSUE TITLE
Installation fails on Ubuntu / Node >=7.x

### ISSUE THREAD

**Issue by zikalino** [fearthecowboy/dotnet#1]
I am wondering if anyone is having this problem.
I can install dotnet-2.0.0 on node 6.x and below, but when Node version is 7 or above (tried with 7, 8 and 9).

Funny thing is that the same procedure causes no problems at all when building Docker container.

Steps to reproduce are quite clean:

(1)	Create Ubuntu Server 16.04 LTS on Azure
(2)	Install Node.js:
**curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs**
(3)	Try to install dotnet:
**sudo npm install -g dotnet-2.0.0**

And I am getting following error:

/usr/bin/dotnet -> /usr/lib/node_modules/dotnet-2.0.0/dist/call.js
/usr/bin/dotnet-run -> /usr/lib/node_modules/dotnet-2.0.0/dist/call.js
/usr/bin/dotnet-run-2.0.0 -> /usr/lib/node_modules/dotnet-2.0.0/dist/call.js
/usr/bin/install-dotnet-runtime -> /usr/lib/node_modules/dotnet-2.0.0/dist/app.js

> dotnet-2.0.0@1.4.4 postinstall /usr/lib/node_modules/dotnet-2.0.0
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/node ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.0.0@1.4.4 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dotnet-2.0.0@1.4.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zim/.npm/_logs/2018-01-26T02_34_25_999Z-debug.log

**Comment by fearthecowboy** [comment]
O_O Weird.

I'll have to take a look...

**Comment by zikalino** [comment]
Yesterday i have also tried to create my container using Travis CI, and Dockerfile that works on Windows doesn't on Travis.
