### ISSUE TITLE
Installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by andybeak** [fearthecowboy/dotnet#2]
I'm using current versions of the tooling and Ubuntu 18.04, as below.
```
$ node --version
v11.3.0
$ npm --version
6.4.1
$ uname --all
Linux it-00511 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
When installing there is an error thrown, as below:

```
$ sudo npm i -g dotnet-2.1 
/usr/bin/dotnet-run-2.1 -> /usr/lib/node_modules/dotnet-2.1/dist/call.js
/usr/bin/dotnet -> /usr/lib/node_modules/dotnet-2.1/dist/call.js
/usr/bin/install-dotnet-runtime -> /usr/lib/node_modules/dotnet-2.1/dist/app.js
/usr/bin/dotnet-run -> /usr/lib/node_modules/dotnet-2.1/dist/call.js

> dotnet-2.1@2.1.0 postinstall /usr/lib/node_modules/dotnet-2.1
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.1@2.1.0 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dotnet-2.1@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andrew/.npm/_logs/2018-12-16T14_05_32_648Z-debug.log
```

**Comment by andybeak** [comment]
A workaround is to avoid installing it globally.

I'm installing it to use botdispatch.  If I install dotnet-2.1 locally into my project node_modules then I can also install botdispatch locally.

**Comment by sunilbinghamton** [comment]
Yes. The work around worked. Thanks.
